version: "3"
services:
  gitea_ubuntu:
    build: ./gitea
    container_name: gitea_ubuntu
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
